# Generated by Django 5.2 on 2025-04-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_fruit_description_remove_saison_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupressionFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supressionfruits', to='catalogue.fruit')),
            ],
        ),
    ]
