# Generated by Django 5.2 on 2025-04-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_remove_fruit_prix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupressionFruit',
        ),
    ]
